import type { TourRegion } from "@/lib/regions-shared";

export function buildRegionsSeed(): TourRegion[] {
  return [
    {
      id: "misir",
      name: "Mısır",
      cardLabel: "MISIR",
      homeTitle: "Tarihin Gizemi: Mısır Turları",
      homeVariant: "dark",
      sortOrder: 1,
      published: true,
      showOnHome: true,
      showInSearch: true,
      showInHero: true,
      heroTitle: "Mısır",
      heroSubtitle: "Piramitler & Nil'in Büyüsü",
      heroPrice: "€899",
      heroPeriod: "7 gece",
      heroImage:
        "https://images.unsplash.com/photo-1539768942893-daf53e448371?w=1200&q=80&auto=format&fit=crop",
      icon: "pyramid",
    },
    {
      id: "balkanlar",
      name: "Balkanlar",
      cardLabel: "BALKANLAR",
      homeTitle: "Kültür Köprüsü: Balkanlar",
      homeVariant: "light",
      sortOrder: 2,
      published: true,
      showOnHome: true,
      showInSearch: true,
      showInHero: true,
      heroTitle: "Balkanlar",
      heroSubtitle: "Tarih & Doğa Harmanı",
      heroPrice: "€699",
      heroPeriod: "6 gece",
      heroImage: "/images/tours/balkanlar-mostar.png",
      icon: "mountain-snow",
    },
    {
      id: "dubai",
      name: "Dubai",
      cardLabel: "DUBAI",
      homeTitle: "Lüks & Macera: Dubai Turları",
      homeVariant: "dark",
      sortOrder: 3,
      published: true,
      showOnHome: true,
      showInSearch: true,
      showInHero: true,
      heroTitle: "Dubai",
      heroSubtitle: "Çölün İncisi & Lüks",
      heroPrice: "€1.299",
      heroPeriod: "5 gece",
      heroImage:
        "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80&auto=format&fit=crop",
      icon: "building-2",
    },
    {
      id: "umre",
      name: "Umre",
      cardLabel: "UMRE",
      homeTitle: "Huzura Yolculuk: Umre Programları",
      homeVariant: "light",
      sortOrder: 4,
      published: true,
      showOnHome: true,
      showInSearch: true,
      showInHero: true,
      heroTitle: "Umre",
      heroSubtitle: "Kutsal Topraklar & Huzur",
      heroPrice: "$749",
      heroPeriod: "10 gece",
      heroImage:
        "https://images.unsplash.com/photo-1564769625905-50e93615e769?w=1600&q=85&auto=format&fit=crop",
      icon: "moon-star",
    },
    {
      id: "yurt-ici",
      name: "Yurt İçi",
      cardLabel: "YURT İÇİ",
      homeTitle: "Vatanın Kalbi: Edirne & Trakya",
      homeVariant: "light",
      sortOrder: 5,
      published: true,
      showOnHome: true,
      showInSearch: true,
      showInHero: true,
      heroTitle: "Yurt İçi",
      heroSubtitle: "Edirne & Trakya Keşfi",
      heroPrice: "₺4.999",
      heroPeriod: "3 gece",
      heroImage:
        "https://images.unsplash.com/photo-1662555025766-2bb053a30e9c?w=1600&q=85&auto=format&fit=crop",
      icon: "map-pinned",
    },
  ];
}
